trigger:
  branches:
    include:
    - main
    - releases/*
    exclude:
    - releases/old*

pool:
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'  # Make sure this points to your actual pom.xml
    goals: 'clean package'   # This will build your jar and place it in the target directory
    publishJUnitResults: false  # If you have JUnit tests, set this to true
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false  # Set to false if you don't need SonarQube
    sqMavenPluginVersionChoice: 'latest'
    jdkVersionOption: '17'  # Set to '17' to match your Java Tool Installer
    jdkArchitectureOption: 'x64'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub_sc'
    repository: 'devops839/voting-app-java'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'