trigger:
  - main

pool:
  vmImage: ubuntu-latest  # Set the image to be used for the build

variables:
  tags: $(Build.BuildId)

stages:
  - stage: DockerBuild
    displayName: Build stage
    jobs:
      - job: DockerBuild
        displayName: Build Docker Image
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'demoacr839'
              repository: 'demoacr839/voting'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: $(tags)
  
  - stage: PushToACR
    displayName: Pushing To ACR
    dependsOn: DockerBuild  # Ensure the PushToACR stage depends on DockerBuild stage
    jobs:
      - job: PushToACR
        displayName: Pushing To ACR
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'ado_sc'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              # Login to Azure Container Registry (ACR)
              az acr login -n demoacr839
              
              # Push the built Docker image using the 'tags' variable
              docker push demoacr839/voting-app:$(tags)