trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  tag: $(Build.BuildId)
  acrName: demoacr839
  aksResourceGroup: demo-aks-rg
  aksCluster: demo-aks
  namespace: default

stages:
  - stage: BuildPushImage
    displayName: Build & Push Docker Image
    jobs:
      - job: Build_Image
        displayName: Build & Push Docker Image
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'ado_sc'  # Azure service connection
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              docker build -t $(acrName).azurecr.io/app:$(tag) .
              az acr login -n $(acrName)
              docker push $(acrName).azurecr.io/app:$(tag)

  - stage: DeployToAKS
    displayName: Deploy to AKS
    jobs:
      - job: DeployToAKS
        displayName: Deploying to AKS
        steps:
        - task: Kubernetes@1
          inputs:
            connectionType: 'Azure Resource Manager'
            azureSubscriptionEndpoint: 'ado_sc'
            azureResourceGroup: $(aksResourceGroup)
            kubernetesCluster: $(aksCluster)
            namespace: $(namespace)
            command: 'apply'
            useConfigurationFile: true
            configuration: 'k8s/vote_deploy.yaml'
            arguments: |
              -f k8s/vote_deploy.yaml
              --set image.tag=$(tag)
              --set acrName=$(acrName)
