trigger:
  - main

pool:
  vmImage: ubuntu-latest  # Set the image to be used for the build

variables:
  tags: $(Build.BuildId)  # Tag with build ID

stages:
  - stage: Build_Image
    displayName: Build Docker Image
    jobs:
      - job: Build_Image
        displayName: Build Docker Image
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo "Building Docker image with tag $(tags)"
              docker build -t demoacr839/voting-app:$(tags) .
              docker tag demoacr839/voting-app:$(tags) demoacr839/voting-app:latest  # Optional: Tag as latest as well

  - stage: PushToACR
    displayName: Push Docker Image to ACR
    dependsOn: Build_Image  # Ensure the PushToACR stage runs after Docker build
    jobs:
      - job: PushToACR
        displayName: Push Docker Image to ACR
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'ado_sc'        # Azure subscription service connection
              scriptType: 'bash'                 # Use bash scripting
              scriptLocation: 'inlineScript'     # Inline script
              inlineScript: |
                az acr login -n demoacr839
                docker images
                docker push demoacr839/voting-app:$(tags)
                docker push demoacr839/voting-app:latest
