trigger:
  - main

pool:
  vmImage: ubuntu-latest  # Set the image to be used for the build

variables:
  tags: $(Build.BuildId)  # Tag with build ID

stages:
  - stage: Build_Image
    displayName: Build Docker Image
    jobs:
      - job: Build_Image
        displayName: Build Docker Image
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo "Building Docker image with tag $(tags)"
              # Build the Docker image and tag it with the build ID and 'latest'
              docker build -t demoacr839.azurecr.io/voting-app:$(tags) .
              docker tag demoacr839.azurecr.io/voting-app:$(tags) demoacr839.azurecr.io/voting-app:latest  # Tag as 'latest' as well
              # List Docker images to confirm successful build
              docker images

  - stage: PushToACR
    displayName: Push Docker Image to ACR
    dependsOn: Build_Image  # Ensure the PushToACR stage runs after Docker build
    jobs:
      - job: PushToACR
        displayName: Push Docker Image to ACR
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'ado_sc'        # Azure subscription service connection
              scriptType: 'bash'                 # Use bash scripting
              scriptLocation: 'inlineScript'     # Inline script
              inlineScript: |
                # Login to Azure Container Registry (ACR)
                az acr login -n demoacr839
                
                # Check if the image exists locally
                echo "Listing all local Docker images"
                docker images
                
                # Ensure the image is tagged correctly before pushing
                docker push demoacr839.azurecr.io/voting-app:$(tags)   # Push with the build ID tag
                docker push demoacr839.azurecr.io/voting-app:latest    # Push with the 'latest' tag
