trigger:
  - main
pool:
  vmImage: ubuntu-latest  # Set the image to be used for the build
variables:
  tags: $(Build.BuildId)  # Define the 'tags' variable using Build ID

stages:
  - stage: DockerBuild
    displayName: Build stage
    jobs:
      - job: DockerBuild
        displayName: Build Docker Image
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'demoacr839'
              repository: 'voting-app'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: 'demoacr839.azurecr.io/app$(tags)'

  - stage: PushToACR
    displayName: Pushing To ACR
    dependsOn: DockerBuild  # Ensure the PushToACR stage depends on DockerBuild stage
    jobs:
      - job: PushToACR
        displayName: Pushing To ACR
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'ado_sc'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az acr login -n demoacr839
              docker push demoacr839/voting-app:$(tags)