trigger:
  branches:
    include:
      - main
      - releases/*
    exclude:
      - releases/old*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: InstallJava
    displayName: 'Install Java 17'
    jobs:
      - job: InstallJavaJob
        steps:
          - task: JavaToolInstaller@1
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
            name: InstallJava17

  - stage: BuildAndTest
    displayName: 'Build and Package with Maven, Run SonarQube Analysis'
    dependsOn: InstallJava
    jobs:
      - job: BuildAndTestJob
        steps:
          # Set JAVA_HOME to the path of Java 17 installed by the previous task
          - script: |
              echo "JAVA_HOME is set to: $(JAVA_HOME)"
              echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME)"
            displayName: 'Set JAVA_HOME for Maven'
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'Custom'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

  - stage: DockerBuildAndPush
    displayName: 'Docker Build and Push'
    dependsOn: BuildAndTest
    jobs:
      - job: DockerBuildAndPushJob
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'dockerhub_sc'
              repository: 'pavan539/voting-app-java'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: 'latest'
