trigger:
  - main

pool:
  vmImage: ubuntu-latest  # Set the image to be used for the build

variables:
  tag: $(Build.BuildId)  # Tag with build ID

stages:
  - stage: Build_Image
    displayName: Build Docker Image
    jobs:
      - job: Build_Image
        displayName: Build Docker Image
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'ado_sc'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              docker build -t demoacr839.azurecr.io/app:$(tag) .
              az acr login -n demoacr839
              docker push demoacr839.azurecr.io/app:$(tag)
