trigger:
  - main

pool:
  vmImage: ubuntu-latest  # Set the image to be used for the build

variables:
  acrName: demoacr839
  tag: $(Build.BuildId)


stages:
  - stage: BuildPushImage
    displayName: Build&Push Docker Image
    jobs:
      - job: Build_Image
        displayName: Build&Push Docker Image
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: 'ado_sc'
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              docker build -t demoacr839.azurecr.io/app:$(tag) .
              az acr login -n demoacr839
              docker push demoacr839.azurecr.io/app:$(tag)

  - stage: DeployToAKS
    displayName: Deploying To AKS
    jobs:
      - job: DeployToAKS
        displayName: Deploying To AKS
        steps:
        - task: Kubernetes@1
          inputs:
            connectionType: 'Azure Resource Manager'
            azureSubscriptionEndpoint: 'ado_sc'
            azureResourceGroup: 'demo-aks-rg'
            kubernetesCluster: 'demo-aks'
            namespace: 'default'
            command: 'apply'
            useConfigurationFile: true
            configuration: 'k8s'
            arguments: '-f k8s/vote_deploy.yaml --set image.tag=$(Build.BuildId) --set acrName=demoacr839'
            containerRegistryType: 'Azure Container Registry'
