apiVersion : apps/v1
kind: Deployment
metadata:
  name: aksacrpoc 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksacrpoc
  template:
    metadata:
      labels:
        app: aksacrpoc 
    spec:
      containers:
        - name: aksacrpoc 
          image: demoacr839.azurecr.io/aksacrpoc
          ports:
          - containerPort: 8080